packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  cpu-features: true
  electron: true
  electron-winstaller: true
  es5-ext: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  ssh2: true
